// CHALLENGE 
//
// 1. CREATE A NEW FILE CALLED NOTES.JS

const getNotes = function() {
    return "Your notes...."
}

module.exports =  getNotes
// 2. CREATE GETNOTES FUNCTION THAT RETURNS "YOUR NOTES..."
// 3. EXPORT GETNOTES FUNCTION
// 4. FROM APP,JS, LOAD IN AND CALL THE FUNCTION PRINTING MESSAGE TO CONSOLE